import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import Provider from '@/components/Provider';
import { Toaster } from '@/components/ui/toaster';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-white text-gray-900`}>
                <Provider>
                    <Navbar />
                    <div className="flex h-screen pt-16 overflow-hidden">
                        <Sidebar />
                        <div className="flex-1 overflow-y-auto p-6">
                            {children}
                        </div>
                    </div>
                    <Toaster />
                </Provider>
            </body>
        </html>
    );
}
